language: python

python:
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"

sudo: required

script:
  - git clone --recursive https://github.com/PedalPi/Physical.git Physical --depth=1
  - cd Physical
  - python setup.py develop
